### ISSUE TITLE
Use Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by shaneholder** [RickStrahl/Westwind.Utilities#15]
According to [Microsoft](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/) Microsoft.Data.SqlClient is the new client to use for SQL access.  I ran into an issue with Westwind.Globalization when trying to use an Azure Active Directory Connection string which uses _Authentication=Active Directory Password_ to configure access.  I traced the problem to DbConnectionOptions not supporting that keyword, see exception below

```
System.ArgumentException
  HResult=0x80070057
  Message=Keyword not supported: 'authentication'.
  Source=System.Data.SqlClient
  StackTrace:
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
```

Any thoughts on switching to the new SqlClient assembly?

Regards,
Shane Holder

**Comment by RickStrahl** [comment]
Thanks Shane for your PR. I have integrated the changes althogh I ended up not using your PR due to flag differences. Same idea though. Thanks.
