### ISSUE TITLE
After upgrade from .NET Framework, AppConfiguration causes a NullReferenceException on app startup

### ISSUE THREAD

**Issue by LyndonGingerich** [RickStrahl/Westwind.Utilities#28]
I am upgrading a project using `AppConfiguration` from .NET Framework 4.7.2 to .NET 8.0. After the upgrade, I get this pop-up:
![image](https://github.com/user-attachments/assets/91ada194-0d1d-4deb-922d-681de81cd4e4)
And the app fails to run.

Using the decompiler, I found that my `AppConfiguration` type is being loaded from `applicationConfiguration.json`. I store my settings in `app.config`. `applicationConfiguration.json` has _most_ of the same field names, but all the booleans are set to `false` and the strings to `null`. And so my app, which is expecting configuration to be loaded from XML with `""` as the default value for strings instead of `null`, throws an exception.

What has changed? How should I update my code? I didn't see releases on this repository or release notes on the tags or anything.

**Comment by LyndonGingerich** [comment]
This is on WestWind.Utilities 3.0.22.

**Comment by LyndonGingerich** [comment]
Upgrading to WestWind.Utilities 5.0.8 does not change the behavior.

**Comment by LyndonGingerich** [comment]
This is interesting:
```csharp

        /// <summary>
        /// Override this method to use a specialized configuration provider for your config class
        /// when no explicit provider is passed to the Initialize() method.
        /// </summary>
        /// <param name="sectionName">Optional section name that was passed to Initialize()</param>
        /// <param name="configData">Optional config data that was passed to Initialize()</param>
        /// <returns>Instance of configuration provider</returns>
        protected virtual IConfigurationProvider OnCreateDefaultProvider(string sectionName, object configData)
        {
			// dynamically construct the generic provider type
#if NETFRAMEWORK
			var providerType = typeof(ConfigurationFileConfigurationProvider<>);
#else
			var providerType = typeof(JsonFileConfigurationProvider<>);
#endif
			var type = GetType();
            Type typeProvider = providerType.MakeGenericType(type);

            var provider = Activator.CreateInstance(typeProvider) as IConfigurationProvider;

            // if no section name is passed it goes into standard appSettings
            if (!string.IsNullOrEmpty(sectionName))
                provider.ConfigurationSection = sectionName;

            return provider;
        }
```
Maybe the issue is the move from `ConfigurationFileConfigurationProvider` to `JsonFileConfigurationProvider`?

**Comment by LyndonGingerich** [comment]
Hmm. There appears to be some curious use of `System.Configuration.NameValueSectionHandler`. Maybe that is causing issues.

**Comment by RickStrahl** [comment]
The old .NET XML provider doesn't work under .NET Core so you have to switch to a different provider - the default provider for .NET Core is the JsonFile provider.

**Comment by LyndonGingerich** [comment]
All right, I'll migrate. Could we document this? The [current documentation](https://docs.west-wind.com/westwind.utilities/_2le027umn.htm) seems to be written exclusively for .NET Framework.
