### ISSUE TITLE
403 Forbidden Access for a lot of the links on the main page

### ISSUE THREAD

**Issue by steveculshaw** [RickStrahl/Westwind.Utilities#3]
Getting a 403 when trying to go through the links on the main page, e.g. 
usage documentation ... http://west-wind.com/westwindtoolkit/docs?page=_3rg13chn1.htm
and the links to the individual classes ... https://west-wind.com/westwindtoolkit/docs/?topic=Class%20StringUtils&topic=Class%20StringUtils

But the class documentation link works ... http://west-wind.com/westwindtoolkit/docs/_3rg13chn1.htm

**Comment by RickStrahl** [comment]
Sorry for the delay. Updated new to new docs which live here now:

https://docs.west-wind.com/westwind.utilities/

Will work through the links here to make sure they are up to date. Thanks...
