### ISSUE TITLE
in the time string utils - converting time entry to time

### ISSUE THREAD

**Issue by weedkiller** [RickStrahl/Westwind.Utilities#5]
Hi, I am finding your lib helpful. Particularly when using it on time data input in a text box. For e.g. a time sheet where people sometimes enter 10.25 or 10,25 or 10:25 -  it would be helpful if we could get this input normalized to time volumes

**Comment by RickStrahl** [comment]
Can you be more specific what you mean? Normalize what exactly?

decimal time to HH:mm?

**Comment by weedkiller** [comment]
user entry with various formats to -> standard parse-able time/hours. For e.g so we know how much time they worked.
