### ISSUE TITLE
Deprecate SmtpClientNative for MailKit

### ISSUE THREAD

**Issue by jzabroski** [RickStrahl/Westwind.Utilities#6]

**Comment by RickStrahl** [comment]
Not gonna happen. The point of this library originally was to provide a self-contained SMTP library with an easy interface before SmtpClient existed. Then it was modified to work with SmtpClient. I don't want to add additional dependencies to the library.

If you want Mailkit behavior/features, then just use Mailkit directly, after all it has a clean front end API.

**Comment by jzabroski** [comment]
I was just suggesting you mark it as Obsolete and suggest clients upgrade to MailKit.  Agree on everything you said

**Comment by jzabroski** [comment]
I don't use this library interface
