### ISSUE TITLE
Update HtmlUtils.cs to fix XSS Attack , it's different between Westwind.Utilities.HtmlEncode and System.Web.HttpUtility.HtmlEncode on `'`.

### ISSUE THREAD

**Issue by shps951023** [RickStrahl/Westwind.Utilities#8]
[Update HtmlUtils.cs to fix XSS Attack , it's different between Westwind.Utilities.HtmlEncode and System.Web.HttpUtility.HtmlEncode on `'`. by shps951023 · Pull Request #7 · RickStrahl/Westwind.Utilities](https://github.com/RickStrahl/Westwind.Utilities/pull/7)

it's different between Westwind.Utilities.HtmlEncode and System.Web.HttpUtility.HtmlEncode  on `'`.

```C#
	var HttpUtilityEncodeResult = System.Web.HttpUtility.HtmlEncode("alert('XSS Attack')"); //"alert(&#39;XSS Attack&#39;)"
	var WestwindEncodeResult = Westwind.Utilities.HtmlUtils.HtmlEncode("alert('XSS Attack')"); //"alert('XSS Attack')"
```
![](https://i.imgur.com/vuCWruw.png)

**Comment by RickStrahl** [comment]
Fixed in #7
